In [8]:
import pandas as pd

#Task 3

ratings_3 = pd.read_csv("ratings_adv.csv")

ratings_3["New_time"] = pd.to_datetime(ratings_3.timestamp, unit='s')
#print(ratings_3.head(50))

dataframe_33 = ratings_3.groupby(['userId'])['rating'].sum().reset_index(name = 'summ')               
dataframe_44 = dataframe_33.loc[(dataframe_33.summ > 100)]
list_3 = list(dataframe_33.loc[(dataframe_33.summ > 100)].userId)

for element in list_3:
    if element in dataframe_33.userId:
        #print(element, " @@@@ ")
        #command below gives warning in Jupiter but works fine in PyCharm
        #but I cannot figure out how to do it using .loc since filtering should be done on 'userId' and 
        #and then max val picked from 'New_time'
        dataframe_44["interval"] = (ratings_3.groupby(['userId'])['New_time'].max()) - (ratings_3.groupby(['userId'])['New_time'].min())
       
print(dataframe_44.head(50))

<ipython-input-8-1e96d9f6b5b8>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe_44["interval"] = (ratings_3.groupby(['userId'])['New_time'].max()) - (ratings_3.groupby(['userId'])['New_time'].min())

    userId    summ           interval
1        2   265.0    0 days 00:01:37
2        3   182.0    0 days 00:14:11
3        4   887.0    0 days 19:46:38
4        5   391.0    2 days 08:32:40
5        6   143.5    0 days 00:35:01
6        7   305.0   13 days 00:13:42
7        8   448.5    0 days 00:43:08
8        9   169.0    0 days 23:39:47
9       10   170.0    5 days 17:32:48
10      11   155.0    0 days 00:26:33
11      12   168.0    0 days 00:30:40
12      13   198.5  146 days 06:43:31
14      15  4457.0    0 days 00:11:19
15      16   119.5 5455 days 22:38:16
16      17  1359.0  472 days 01:49:05
17      18   165.0    0 days 02:14:13
18      19  1495.0    0 days 23:40:50
19      20   322.5    0 days 01:28:02
20      21   568.0  170 days 00:05:02
21      22   720.5   15 days 19:17:12
22      23  2637.5    1 days 01:24:51
25      26   596.5    0 days 00:17:58
27      28   214.0    0 days 01:36:47
29      30  3806.5    0 days 00:47:43
30      31   287.5 1340 days 21:11:16
31      32   176.0    7 days 02:51:17
32      33   452.0    0 days 00:09:33
33      34   736.0   50 days 03:23:31
35      36   376.0    0 days 00:00:29
36      37   130.0   68 days 20:34:50
37      38   476.5    0 days 01:06:58
38      39   235.0  694 days 02:47:45
39      40   194.0   11 days 17:01:55
40      41   769.5    0 days 00:07:43
41      42   281.0  184 days 09:08:15
42      43   330.0    0 days 00:05:03
45      46   193.0    0 days 00:10:04
46      47   147.0    0 days 01:05:20
47      48  1803.0    0 days 00:19:49
48      49   343.0 1577 days 17:32:57
49      50   151.0    0 days 00:35:35
50      51   123.0    0 days 00:09:16
51      52   251.0    0 days 00:09:42
52      53   128.0    0 days 02:08:33
53      54   167.0    0 days 00:28:59
54      55   138.0    0 days 01:12:21
55      56  1887.0    0 days 00:08:17
56      57   827.0   99 days 02:55:20
57      58   249.0    0 days 01:12:03
58      59   240.5    0 days 00:17:26

In [3]:
import pandas as pd

#Task 4

rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)

auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)

air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)

client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1',
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)

table_2_revenues = pd.merge(rzd, auto, on = 'client_id', how = 'outer')
table_3_revenues = pd.merge(table_2_revenues, air, on = 'client_id', how = 'outer')
print(table_3_revenues)

table_3_revenues_plus_address = pd.merge(table_3_revenues, client_base, on = 'client_id', how = 'outer')
print(table_3_revenues_plus_address)

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           NaN          NaN
1        112       2810.0           NaN          NaN
2        113      10283.0       57483.0          NaN
3        114       5774.0          83.0          NaN
4        115        981.0         912.0         81.0
5        116          NaN        4834.0          4.0
6        117          NaN          98.0         13.0
7        118          NaN           NaN        173.0
   client_id  rzd_revenue  auto_revenue  air_revenue          address
0        111       1093.0           NaN          NaN  Комсомольская 4
1        112       2810.0           NaN          NaN   Энтузиастов 8а
2        113      10283.0       57483.0          NaN  Левобережная 1а
3        114       5774.0          83.0          NaN          Мира 14
4        115        981.0         912.0         81.0        ЗЖБИиДК 1
5        116          NaN        4834.0          4.0    Строителей 18
6        117          NaN          98.0         13.0  Панфиловская 33
7        118          NaN           NaN        173.0     Мастеркова 4